debug https://github.com/Altinity/clickhouse-backup/issues/888, use dockerPool instead of up+down, remove partial download metadata for object disk required backup during `restore`

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -295,7 +295,7 @@ jobs:
           QA_GCS_OVER_S3_SECRET_KEY: ${{ secrets.QA_GCS_OVER_S3_SECRET_KEY }}
           QA_GCS_OVER_S3_BUCKET: ${{ secrets.QA_GCS_OVER_S3_BUCKET }}
         run: |
-          set -x
+          set -xe
           echo "CLICKHOUSE_VERSION=${CLICKHOUSE_VERSION}"
           echo "GCS_TESTS=${GCS_TESTS}"
 
@@ -316,6 +316,23 @@ jobs:
           export CUR_DIR="$(pwd)/test/integration"
           export CLICKHOUSE_BACKUP_BIN="$(pwd)/clickhouse-backup/clickhouse-backup-race"
           docker compose -f "${CUR_DIR}/${COMPOSE_FILE}" --progress=quiet pull
+          
+          pids=()
+          for ((i = 1; i <= RUN_PARALLEL; i++)); do
+            docker compose -f ${CUR_DIR}/${COMPOSE_FILE} --project-name project${i} --progress plain up -d &
+            pids+=($!)
+          done
+          
+          
+          for pid in "${pids[@]}"; do
+            if wait "$pid"; then
+                echo "$pid docker compose up successful"
+            else
+                echo "$pid the docker compose up failed. Exiting."
+                exit 1  # Exit with an error code if any command fails
+            fi
+          done
+          
           go test -parallel ${RUN_PARALLEL} -timeout 60m -failfast -tags=integration -run "${RUN_TESTS:-.+}" -v test/integration/integration_test.go
       - name: Format integration coverage
         env:
